---
apiVersion: v1
kind: Pod
metadata:
  name: controller
  namespace: knative-whisk
  labels:
    app: controller

spec:  

  volumes:
  - name: git-data
    emptyDir: {}

  imagePullSecrets:
  - name: docker-registry-secret

  containers:
  - name: git-server
    image: "actionloop/kwhisk-controller:latest"
    imagePullPolicy: Always
    ports:
    - containerPort: 9418
      name: git
    volumeMounts:
    - name: git-data
      mountPath: /git
    command:
      - /usr/bin/git
      - daemon
    args: 
     - --verbose 
     - --export-all 
     - --base-path=/git
  - name: kwhisk-controller
    image: actionloop/kwhisk-controller:latest
    imagePullPolicy: Always
    command: ["/bin/controller"]
    ports:
    - containerPort: 8080
      name: controller
    volumeMounts:
    - name: git-data
      mountPath: /git
    env:
    - name: KW_REPO
      value: /git
