---
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: knative-whisk
  labels:
     app: hello-world
spec:
  imagePullSecrets:
  - name: docker-registry-secret  
  containers:
  - name: hello
    image: registry.kube-system/actionloop/hello-world-3:latest
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: knative-whisk
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
