---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-role
subjects:
- kind: ServiceAccount
  name: kubectl-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubectl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubectl
    spec:
      serviceAccountName: kubectl-role
      containers:
      - name: kubectl
        imagePullPolicy: Always
        image: msciab/kubectl
        command: [ "tail" ]
        args: [ "-f", "/dev/null" ]
