name = "OpenWhiskKnative"
uuid = "7f8bdcac-7eed-11e9-1661-ef60a6f17785"
authors = ["Michele Sciabarra <msciabarra@apache.org>"]
version = "0.1.0"

[deps]
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
