---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kwhisk-install-role
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kwhisk-install-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: kwhisk-install-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: knative-install
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: knative-install
    spec:
      serviceAccountName: kwhisk-install-role
      containers:
      - name: setup
        imagePullPolicy: Always
        image: actionloop/knative-installer:latest
      restartPolicy: Never
  backoffLimit: 4
