// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllRulesHandlerFunc turns a function with the right signature into a get all rules handler
type GetAllRulesHandlerFunc func(GetAllRulesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllRulesHandlerFunc) Handle(params GetAllRulesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAllRulesHandler interface for that can handle valid get all rules params
type GetAllRulesHandler interface {
	Handle(GetAllRulesParams, interface{}) middleware.Responder
}

// NewGetAllRules creates a new http.Handler for the get all rules operation
func NewGetAllRules(ctx *middleware.Context, handler GetAllRulesHandler) *GetAllRules {
	return &GetAllRules{Context: ctx, Handler: handler}
}

/*GetAllRules swagger:route GET /namespaces/{namespace}/rules Rules getAllRules

Get all rules

Get all rules

*/
type GetAllRules struct {
	Context *middleware.Context
	Handler GetAllRulesHandler
}

func (o *GetAllRules) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllRulesParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
