---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        ports:
        - containerPort: 3000
          name: gitea
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /data
          name: git-data
      volumes:
      - name: git-data
        emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: gitea-service
spec:
  selector:
    app: gitea
  ports:
  - name: gitea
    port: 3000
    targetPort: 3000
  - name: gitea-ssh
    port: 22
    targetPort: 22
---
kind: Service
apiVersion: v1
metadata:
  name: gitea-service
spec:
  type: NodePort
  selector:
    app: gitea
  ports:
  - name: gitea
    port: 3000
    nodePort: 30180
  - name: gitea-ssh
    port: 22
    nodePort: 30122
