---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: name
    image: gcr.io/kaniko-project/executor:latest
    command: ["tail", "-f", "/dev/null"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: docker-config
      mountPath: /root/.docker
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
         name: docker-registry-secret
         items:
         - key: .dockerconfigjson
           path: .docker/config.json
