apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     app: nginx
spec:
  containers:
  - name: name
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
         name: docker-registry-secret
         items:
         - key: .dockerconfigjson
           path: config.json
