// Code generated by go-swagger; DO NOT EDIT.

package activations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetActivationLogsHandlerFunc turns a function with the right signature into a get activation logs handler
type GetActivationLogsHandlerFunc func(GetActivationLogsParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetActivationLogsHandlerFunc) Handle(params GetActivationLogsParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetActivationLogsHandler interface for that can handle valid get activation logs params
type GetActivationLogsHandler interface {
	Handle(GetActivationLogsParams, interface{}) middleware.Responder
}

// NewGetActivationLogs creates a new http.Handler for the get activation logs operation
func NewGetActivationLogs(ctx *middleware.Context, handler GetActivationLogsHandler) *GetActivationLogs {
	return &GetActivationLogs{Context: ctx, Handler: handler}
}

/*GetActivationLogs swagger:route GET /namespaces/{namespace}/activations/{activationid}/logs Activations getActivationLogs

Get the logs for an activation

Get activation logs information.

*/
type GetActivationLogs struct {
	Context *middleware.Context
	Handler GetActivationLogsHandler
}

func (o *GetActivationLogs) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetActivationLogsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
