apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker-registry-secret
  namespace: knative-whisk
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5Lmt1YmUtc3lzdGVtIjp7InVzZXJuYW1lIjoicmVnaXN0cnkiLCJwYXNzd29yZCI6InBhc3N3b3JkIiwiZW1haWwiOiJrbmF0aXZlQG9wZW53aGlzayIsImF1dGgiOiJjbVZuYVhOMGNuazZjR0Z6YzNkdmNtUT0ifX19
